server.port=8282
server.servlet.context-path=/consumer

spring.application.name=lib-evt-consumer

# Kafka topic properties
#spring.kafka.topic.name=lib-evts-topic
#spring.kafka.topic.nombre-partitions=3
#spring.kafka.topic.nombre-replicas=1

# Dummy Header of Producer record 
#spring.kafka.producer-record.header.key=evt-source
#spring.kafka.producer-record.header.value=scanner

spring.config.activate.on-profile=local
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.IntegerDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id=lib-evts-listeners-grp
#spring.kafka.producer.properties.acks= 1
#spring.kafka.producer.properties.retries= 7
 
#spring.kafka.admin.properties.bootstrap-servers=localhost:9092
#spring.kafka.admin.properties.retries= 7